# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

MM=/usr/bin/gcc
CXX=/usr/bin/gcc
CC=/usr/bin/gcc
AS=/usr/bin/gcc
MXX=/usr/bin/gcc

AR=/usr/bin/ar
SH=/usr/bin/g++
LD=/usr/bin/g++

Funix_CXXFLAGS=-m64 -Iinclude
Funix_CXXFLAGS=-m64 -Iinclude
Funix_LDFLAGS=-m64

default:  Funix

all:  Funix

.PHONY: default all  Funix

Funix: build/linux/x86_64/release/Funix
build/linux/x86_64/release/Funix: build/.objs/Funix/linux/x86_64/release/src/main.cpp.o
	@echo linking.release Funix
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/Funix build/.objs/Funix/linux/x86_64/release/src/main.cpp.o $(Funix_LDFLAGS) > build/.build.log 2>&1

build/.objs/Funix/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo compiling.release src/main.cpp
	@mkdir -p build/.objs/Funix/linux/x86_64/release/src
	@$(CXX) -c $(Funix_CXXFLAGS) -o build/.objs/Funix/linux/x86_64/release/src/main.cpp.o src/main.cpp > build/.build.log 2>&1

clean:  clean_Funix

clean_Funix: 
	@rm -rf build/linux/x86_64/release/Funix
	@rm -rf build/linux/x86_64/release/Funix.sym
	@rm -rf build/.objs/Funix/linux/x86_64/release/src/main.cpp.o

